name: env1
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - alsa-lib=1.2.3.2
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2024.12.14
  - cairo=1.16.0
  - certifi=2024.12.14
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=41.0.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3.2
  - filelock=3.9.0
  - fontconfig=2.13.1
  - freeglut=3.2.1
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - harfbuzz=3.1.1
  - hdf5=1.12.1
  - icu=68.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jasper=2.0.33
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - keyutils=1.6.1
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcurl=8.1.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libglu=9.0.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libogg=1.3.5
  - libopencv=4.5.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=13.8
  - libprotobuf=3.19.6
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lxml=4.8.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numba=0.60.0
  - opencv=4.5.5
  - openh264=2.1.1
  - openssl=1.1.1w
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.5.5
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt=5.12.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=68.0.0
  - sip=6.6.2
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.2
  - tqdm=4.67.1
  - traitlets=5.7.1
  - umap-learn=0.5.7
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - x264=1!161.3030
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.27.2
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - array-record==0.5.1
      - astunparse==1.6.3
      - beartype==0.17.2
      - bokeh==3.2.2
      - click==8.1.6
      - cloudpickle==3.0.0
      - cmake==3.25.0
      - colorcet==3.0.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.0.10
      - dask==2023.10.0
      - datashader==0.15.2
      - datashape==0.5.2
      - deprecated==1.2.14
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.7.0
      - ema-pytorch==0.4.2
      - equinox==0.11.8
      - etils==1.10.0
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - flatbuffers==24.3.25
      - fonttools==4.55.3
      - fsspec==2023.10.0
      - gast==0.6.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-pasta==0.2.0
      - grpcio==1.67.0
      - h5py==3.12.1
      - holoviews==1.18.0
      - hopcroftkarp==1.2.5
      - huggingface-hub==0.23.4
      - hydra-core==1.3.2
      - imageio==2.33.1
      - immutabledict==4.2.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.4.5
      - install==1.3.5
      - ipdb==0.13.13
      - jax==0.4.35
      - jaxlib==0.4.35
      - jaxtyping==0.2.34
      - joblib==1.4.2
      - keras==3.6.0
      - kiwisolver==1.4.8
      - lazy-loader==0.3
      - libclang==18.1.1
      - lightning-utilities==0.11.8
      - linkify-it-py==2.0.2
      - lit==15.0.7
      - llvmlite==0.38.0
      - locket==1.0.0
      - loguru==0.7.2
      - markdown==3.5
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - multipledispatch==1.0.0
      - namex==0.0.8
      - numpy==2.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optree==0.13.0
      - packaging==24.2
      - panda==0.3.1
      - pandas==2.2.3
      - panel==1.2.3
      - param==1.13.0
      - partd==1.4.1
      - pathtools==0.1.2
      - persim==0.3.5
      - pillow==11.0.0
      - plotly==5.16.1
      - promise==2.3
      - protobuf==3.20.3
      - pyarrow==17.0.0
      - pyct==0.5.0
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytz==2024.2
      - pyviz-comms==3.0.0
      - regex==2024.5.15
      - rich==13.7.1
      - ripser==0.6.8
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.12.2
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - simple-parsing==0.1.6
      - simpleitk==2.3.1
      - six==1.17.0
      - smmap==5.0.0
      - tenacity==8.2.3
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-datasets==4.9.6
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.16.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2023.12.9
      - tokenizers==0.19.1
      - toolz==0.12.0
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchmetrics==1.6.0
      - torchvision==0.19.1+cu121
      - transformers==4.41.2
      - triton==3.0.0
      - typeguard==2.13.3
      - typing-extensions==4.9.0
      - tzdata==2024.2
      - uc-micro-py==1.0.2
      - wandb==0.15.8
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - xarray==2023.10.0
      - xyzservices==2023.10.0
      - zipp==3.17.0
